[package]
name = "tempfile"
version = "2.1.4"
authors = ["Steven Allen <steven@stebalien.com>"]
description = "Securely create temporary files."

documentation = "https://stebalien.github.io/tempfile/tempfile/"
repository = "https://github.com/Stebalien/tempfile"
homepage = "http://stebalien.com/projects/tempfile-rs"
keywords = ["tempfile", "tmpfile", "filesystem"]
license = "MIT/Apache-2.0"

build = "build.rs"

[dependencies]
libc = "0.2"
rand = "0.3"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[features]
default=[]

[build-dependencies]
rustc_version = "0.1.4"
