name: Redox CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  redox:
    runs-on: ubuntu-latest
    container: redoxos/redoxer
    steps:
      - name: Install Toolchain
        run: |
          ln -sT /root/.redoxer ~/.redoxer
      - uses: actions/checkout@v6
      - name: Build
        run: redoxer build
      - name: Test
        run: redoxer test --tests # doc tests aren't supported
